### PR TITLE
Get scaled traces for `SpikeSortingView`

### PR DESCRIPTION
**Pull request by khl02007**
Sometimes the spikeinterface recording object is in analog-to-digital converter units rather than physically meaningful units like microvolts. In that case, the recording may have gain parameters that can be applied during calls to `get_traces` to convert the traces to physical units. This change checks if such parameters exist (by calling either `has_scaleable_traces` or `has_scaled` methods) and sets `return_scaled` parameter of `get_traces` to that.

### CODE REVIEW

**Comment by magland** [comment]
@khl02007 I'm fine merging this as long as you've tested it on your end.

**Comment by khl02007** [comment]
Just tried running my branch on two recording objects, [one with scale specified](https://figurl.org/f?v=npm://@fi-sci/figurl-sortingview@12/dist&d=sha1://4f3aa4c072b4d933fcc0c474e5cce7c0501e09e3&label=L14%2020240611%20run_epochs%20probe1%20shank0%20ms4%20scaled&zone=franklab.default) and [one without](https://figurl.org/f?v=npm://@fi-sci/figurl-sortingview@12/dist&d=sha1://20fe7f4f86400364fc4e1cc64da0e890222b631b&label=L14%2020240611%20run_epochs%20probe1%20shank0%20ms4%20unscaled&zone=franklab.default). It seems they both run and are the same except for the scale in the spike amplitude view

**Comment by alejoe91** [comment]
Looks good to me too @khl02007

**Comment by magland** [comment]
Now published as 0.13.5

**Pull request merged**
